### ISSUE TITLE
Errors in log showing up last couple of days.

### ISSUE THREAD

**Issue by SteveCrookJr** [lstern/SWProxy-plugins#48]
Some errors have started showing up in the log the last couple of days. Just wanting to inform in case there is an issue.

INFO:SWProxy:Found Summoners War API request : BattleScenarioStart
INFO:SWProxy:Found Summoners War API request : BattleScenarioResult
WARNING:SWProxy:SwarfarmLogger - Error: ['null value in column "dungeon_id" violates not-null constraint\n', 'DETAIL:  Failing row contains (316752, 17017589, 2016-07-01 16:15:58+00, 0, null, null, null, f, 00:01:26.026, 330, 0, null, null, null, null, 28328, 2).\n', ' null value in column "dungeon_id" violates not-null constraint\n', 'DETAIL:  Failing row contains (316752, 17017589, 2016-07-01 16:15:58+00, 0, null, null, null, f, 00:01:26.026, 330, 0, null, null, null, null, 28328, 2).\n']
INFO:SWProxy:Found Summoners War API request : BattleScenarioStart
INFO:SWProxy:Found Summoners War API request : BattleScenarioResult
Exception in thread Thread-1212:
Traceback (most recent call last):
  File "threading.py", line 810, in **bootstrap_inner
  File "threading.py", line 763, in run
  File "C:\Users\offic\Desktop\SW\plugins\SwarfarmLogger.py", line 67, in process_data
    resp = urllib.urlopen(url, data=urllib.urlencode({'data': data}))
  File "urllib.py", line 89, in urlopen
  File "urllib.py", line 215, in open
  File "urllib.py", line 443, in open_https
  File "httplib.py", line 1049, in endheaders
  File "httplib.py", line 893, in _send_output
  File "httplib.py", line 855, in send
  File "httplib.py", line 1274, in connect
  File "ssl.py", line 352, in wrap_socket
  File "ssl.py", line 579, in __init**
  File "ssl.py", line 808, in do_handshake
IOError: [Errno socket error] [Errno 10054] An existing connection was forcibly closed by the remote host

INFO:SWProxy:Found Summoners War API request : SellRune
INFO:SWProxy:Found Summoners War API request : BattleScenarioStart
INFO:SWProxy:Found Summoners War API request : BattleScenarioResult
INFO:SWProxy:Found Summoners War API request : SellRune
Exception in thread Thread-1223:
Traceback (most recent call last):
  File "threading.py", line 810, in **bootstrap_inner
  File "threading.py", line 763, in run
  File "C:\Users\offic\Desktop\SW\plugins\SwarfarmLogger.py", line 67, in process_data
    resp = urllib.urlopen(url, data=urllib.urlencode({'data': data}))
  File "urllib.py", line 89, in urlopen
  File "urllib.py", line 215, in open
  File "urllib.py", line 443, in open_https
  File "httplib.py", line 1049, in endheaders
  File "httplib.py", line 893, in _send_output
  File "httplib.py", line 855, in send
  File "httplib.py", line 1274, in connect
  File "ssl.py", line 352, in wrap_socket
  File "ssl.py", line 579, in __init**
  File "ssl.py", line 808, in do_handshake
IOError: [Errno socket error] [Errno 10054] An existing connection was forcibly closed by the remote host

INFO:SWProxy:Found Summoners War API request : BattleScenarioStart
INFO:SWProxy:Found Summoners War API request : BattleScenarioResult
WARNING:SWProxy:SwarfarmLogger - Error: ['<html>\r\n', '<head><title>405 Not Allowed</title></head>\r\n', '<body bgcolor="white">\r\n', '<center><h1>405 Not Allowed</h1></center>\r\n', '<hr><center>nginx</center>\r\n', '</body>\r\n', '</html>\r\n']
INFO:SWProxy:Found Summoners War API request : SellRune
INFO:SWProxy:Found Summoners War API request : BattleScenarioStart
INFO:SWProxy:Found Summoners War API request : BattleScenarioResult
WARNING:SWProxy:SwarfarmLogger - Error: ['null value in column "dungeon_id" violates not-null constraint\n', 'DETAIL:  Failing row contains (316767, 17017589, 2016-07-01 16:27:10+00, 0, null, null, null, f, 00:01:54.916, 978, 0, null, null, null, null, 28328, 0).\n', ' null value in column "dungeon_id" violates not-null constraint\n', 'DETAIL:  Failing row contains (316767, 17017589, 2016-07-01 16:27:10+00, 0, null, null, null, f, 00:01:54.916, 978, 0, null, null, null, null, 28328, 0).\n']
INFO:SWProxy:Found Summoners War API request : BattleScenarioStart

**Comment by fperegrinvs** [comment]
I think your google sheet plugin is not properly configured

**Comment by SteveCrookJr** [comment]
Alright. Thanks. It hadn't happened before and just wanted to notify you. I don't use the Sheets plugin, so I'll try to figure out how to disable. :)
