### ISSUE TITLE
SWProxy fails to start: Possible break in dependencies

### ISSUE THREAD

**Issue by feralfenrir** [lstern/SWProxy-plugins#76]
I'm running the latest commit on Debian based linux-4.9.0 x64

When I run SWProxy.py on my Debian distro, it fails to run with the following error:

```
Traceback (most recent call last):
  File "./SWProxy.py", line 14, in <module>
    import gspread
  File "/usr/local/lib/python2.7/dist-packages/gspread/__init__.py", line 21, in <module>
    from .client import Client, authorize
  File "/usr/local/lib/python2.7/dist-packages/gspread/client.py", line 20, in <module>
    from .httpsession import HTTPSession
  File "/usr/local/lib/python2.7/dist-packages/gspread/httpsession.py", line 11, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 73, in <module>
    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
```

I guessing this is breaking because of the use of SSLv3 methods?

**Comment by PeteAndersen** [comment]
This is a known issue with the requests module and Debian distributions. What version of the requests module do you have installed? (run `pip list`). If it's less than 2.6.0, run `pip install -u requests` and try again

**Comment by feralfenrir** [comment]
That sure must be the problem!

The installed version was `requests (2.4.3)`. I uninstalled and reinstalled requests from my distro's repo: python-requests (2.12.4).

This has solved this issue.

Thanks mate!

**Comment by PeteAndersen** [comment]
Great!
