### ISSUE TITLE
KeyError in Guild Battle Logger

### ISSUE THREAD

**Issue by feralfenrir** [lstern/SWProxy-plugins#77]
After a guild battle is done, there seems to be an exception which is not handled:

```
INFO:SWProxy:Found Summoners War API request : BattleGuildWarResult
ERROR:root:Exception while executing plugin "Guild Battle Logger": 2
Traceback (most recent call last):
  File "SWPlugin.py", line 42, in call_plugins
  File "D:\Games\Tools\SWProxy\plugins\GuildBattleLogger.py", line 65, in process_request
    return self.log_end_battle(req_json, resp_json, config)
  File "D:\Games\Tools\SWProxy\plugins\GuildBattleLogger.py", line 147, in log_end_battle
    log_entry['opteam%s' % i] = monster_name(opp_monster_list[i])
KeyError: 2
```

https://wiki.python.org/moin/KeyError

**Comment by feralfenrir** [comment]
This is in the Release version running on Windows 10 x64
