### ISSUE TITLE
SpreadsheetNotFound

### ISSUE THREAD

**Issue by Speedo2k** [lstern/SWProxy-plugins#79]
I createt sheet: Guildwar 03-25-2017 based on pattern. I can see them on feed:
https://spreadsheets.google.com/feeds/spreadsheets
(On feed https://spreadsheets.google.com/feeds cann't see).
But I alwasy get SpreadsheetNotFound in both cases with old and nee feed definition.

INFO:SWProxy:Running Proxy server at 10.0.0.100 on port 8080
INFO:SWProxy:Found Summoners War API request : GetGuildWarBattleLogByGuildId
Guildwar 03-25-2017
Exception in thread Thread-3:
Traceback (most recent call last):
  File "threading.py", line 810, in __bootstrap_inner
  File "threading.py", line 763, in run
  File "d:\SWP\plugins\GWLogger.py", line 328, in log_guildwar
    sheet = self.get_worksheet(self.config['google_key'], self.config['sheet_name'])
  File "d:\SWP\plugins\GWLogger.py", line 88, in get_worksheet
    return gc.open(sheet_name)
  File "site-packages\gspread\client.py", line 152, in open
SpreadsheetNotFound

**Comment by Speedo2k** [comment]
finally work. need to give access to sheet for technical user used in oauth
